### ISSUE TITLE
Битые ссылки на crabik.ru

### ISSUE THREAD

**Issue by SomeoneToIgnore** [CrabikBoards/hardware#1]
На https://crabik.ru/#/ есть две битые ссылки:

* ссылка на GitHub в правом верхнем углу ведёт на https://github.com/kekcheburec/crabik.ru
* ссылка "Купить crabik" ведёт на https://store/ 

Обе невалидны, было бы здорово убрать их или исправить ссылки в них.
Так же было бы здорово иметь возможность сообщать об ошибках на сайте более удобным способом.

**Comment by kekcheburec** [comment]
Спасибо что обратили внимание на это.
Ссылка на репозитории сайта была не битая, сам репозитории был приватный, уже открыл его, все в порядке.
Кнопку для покупки я уберу, т.к. из-за проблем с компонентами у поставщика я занялся другими проектами. Купить плату нельзя, можно только самому заказать и допаять недостающие компоненты.
